### ISSUE TITLE
what should be the Tokenizer path

### ISSUE THREAD

**Issue by kr-sundaram** [keleog/finetune_huggingace_t5#1]
Hello, thanks for making this repository public. I wanna finetune the model for both german to english and english to german translation task. Could you please tell about what should be the tokenizer path?

As you have given "bpe/bpe4000.model" as tokenizer_path in t5_config.yml file, it is appearing to me as path of a sentencepiece model which has been trained for source and target language altogether otherwise there should have been 2 tokenizer_path one for source and other for target, which is generally a good practice to follow.

Thanks for your patience!!

**Comment by keleog** [comment]
Hi,

T-5 was trained on Four languages, per the authors - 

"We use SentencePiece to encode text as . For all experiments, we use a vocabulary of 32,000 wordpieces. Since we ultimately fine-tune our model on English to German, French, and Romanian translation, we also require that our vocabulary covers these non-English languages. To address this, we classified pages from the Common Crawl scrape used in C4 as German, French, and Romanian. Then, we trained our SentencePiece model on a mixture of 10 parts of English C4 data with 1 part each of data classified as German, French or Romanian. This vocabulary was shared across both the input and output of our model. Note that our vocabulary makes it so that our model can only process a predetermined, fixed set of languages."

Hence, you should just leave the tokenizer_path blank as `tokenizer_path: ""` and it will default to using the pre-trained T5 tokenizer. Details of implementation are in this else block https://github.com/keleog/finetune_huggingace_t5/blob/master/src/trainer.py#L40

**Comment by kr-sundaram** [comment]
Thank you so much for your inputs!

I have got some doubts hope you clarify them.

1. According to paper, if T5 has been trained on 4 languages i.e. En, DE, Fr, Ro, how come you are finetuning on your custom dataset like En to Pd, even if you are fine-tuning T5 pretrained model on some new datasets as yours, how have you handled the vocab of Pd language then? and what was the accuracy like bleu score of translation of test dataset i.e. en to pd?

2. Now, I have got new error as below:

Traceback (most recent call last):
  File "finetune_t5.py", line 43, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "finetune_t5.py", line 38, in main
    trainer = Trainer(config, current_experiment_path)
  File "/content/drive/My Drive/finetune_huggingace_t5/src/trainer.py", line 142, in __init__
    self.tokenizer = T5Tokenizer.from_pretrained()
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py", line 1140, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
TypeError: _from_pretrained() missing 1 required positional argument: 'pretrained_model_name_or_path'

Could you please help me in rectifying this?

Thank you for your patience!!

**Comment by keleog** [comment]
1. I used the default pre-trained tokenizer for the four languages on my En to Pd model, but it did not yield very good results. Hence, I decided to train a new BPE model using SentencePiece https://github.com/google/sentencepiece/tree/master/python. This performed better than the default pre-trained tokenizer. 

To answer your question, hugginface allows you to load a trained sentence piece model as you will see in the init function here https://huggingface.co/transformers/_modules/transformers/tokenization_t5.html#T5Tokenizer. This means you can train a new tokenizer from scratch and use it with this T5. 

2. That was due to an error on my path as I had a redundant tokenizer initialization. I have fixed it in this commit https://github.com/keleog/finetune_huggingace_t5/commit/461d9079eb731b3580f862a9142a237695d259e1

**Comment by kr-sundaram** [comment]
Thanks for letting me know every detail of what you did in your project.

1. Now, while running i am getting this new error that says about the truncation. I tried to find on t5_config.yml but i did not get any field related to that. could you please look into this?

I0714 10:32:39.182817 140059848107904 trainer.py:271] Building data generators...
W0714 10:32:52.922687 140059848107904 tokenization_utils_base.py:1447] Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


2. One more thing, In huggingface transformers library MarianMT has introduced more than 1000 NMT models on different language pairs and MarianMT tokenizer scripts are also available. Do you think that we can finetune any particular models trained on a particular bilingual pair?

**Comment by keleog** [comment]
1. Looks like the warning is a huggingface problem as you can see in this issue -https://github.com/huggingface/tokenizers/issues/332. They seem to have fixed it in the master branch but not in the released versions. In order to solve this, you can install an older version of huggingface or install straight from their master branch to avoid this warning

2. Unfortunately, I have not used the MarianMT models in huggingface and cannot provide advice about it.

**Comment by kr-sundaram** [comment]
Thank you very much for all your efforts and advises!

**Comment by kr-sundaram** [comment]
Just one question, while training your sentencepiece model, you had both 'EN' and 'PD' sentences in one file and then you train your model? i mean, you did not train your sentecepiece model only for your 'PD' sentences,, you actually did for both languages together and gave number of vocabulary parameters as 32000 while training?

**Comment by keleog** [comment]
Yes, I concatenated the train set of both PD and EN and trained a shared vocabulary. I also used a BPE vocab size of 4000.

**Comment by kr-sundaram** [comment]
Thanks for letting me know. But, I got some confusion. I did not understand what you mean by 'BPE of vocab size 4000'.

Just wanted to be sure that, you gave value as 4000 in the vocab_size argument while training the sentencepiece model after concatenating train set of both En-Pd, right? and you did not train your sentencepiece model with 32000 vocab_size, right?

**Comment by keleog** [comment]
Yes, I specified the vocab_size argument as 4000.

**Comment by kr-sundaram** [comment]
Thank you for your help!

**Comment by Arij-Aladel** [comment]
@keleog  Thanks for your clarifications. I have a question please since you are using t5model doew your pretrained tokenizer have the same model_max_len as t5model which is 512? I have followed your steps to train the tokenizer on new language but I have got some cuda troubles
